platform :ios, '15.0'

target 'TrackAsiaLive' do
  use_frameworks!

pod 'Alamofire' , '~> 5.6'
pod 'GoogleMaps', '9.3.0'
  
end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
        target.build_configurations.each do |config|
#            config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = '$(inherited)'
            config.build_settings['ARCHS'] = 'arm64 x86_64'
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
            config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
            config.build_settings['ENABLE_BITCODE'] = 'NO'
         end
    end
  end
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64, x86_64"
  end
end


